owner: mybigday
repo: service-uptime

# Add your sites here
sites:
  - name: BRICKS
    method: HEAD
    url: https://display.bricks.tools
  - name: BRICKS Device
    url: https://device.bricks.tools
    expectedStatusCodes:
      - 404
  - name: BRICKS Bank
    url: https://bank.bricks.tools/api/not-found
    expectedStatusCodes:
      - 404
  - name: MyBigDay Group
    url: https://group.mybigday.com.tw
  - name: BotHub (GCP)
    url: https://bothub.mybigday.com.tw
  - name: Media Flow
    url: https://media.bricks.tools
    expectedStatusCodes:
      - 404
  - name: Activity Log
    url: https://activity.bricks.tools
    expectedStatusCodes:
      - 404
  - name: Media Companion
    url: https://media-companion.bricks.tools
    expectedStatusCodes:
      - 500
  - name: Media Resource (Auth0)
    url: https://media-beta.bricks.tw
  - name: MyBigDay User (Legacy)
    url: https://user.mybigday.com.tw
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bricks.tools
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /service-uptime
  logoUrl: https://cdn.mybigday.com.tw/bricks/bricks.png
  name: BRICKS Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
