owner: mybigday
repo: service-uptime

# Add your sites here
sites:
  - name: BRICKS
    method: HEAD
    url: https://display.bricks.tools
  - name: BRICKS BETA
    method: HEAD
    url: https://display-beta.bricks.tools
  - name: BRICKS Bank
    url: https://bank.bricks.tools/update
  - name: BRICKS Bank BETA
    url: https://bank-beta.bricks.tools/update
  - name: MyBigDay Group
    url: https://group.mybigday.com.tw
  - name: MyBigDay Group BETA
    url: https://group-beta.mybigday.com.tw
  - name: BotHub (GCP)
    url: https://bothub.mybigday.com.tw
  - name: BotHub BETA
    url: https://bothub-beta.bricks.tw
  - name: Media Flow BETA
    url: https://media-beta.bricks.tools
    expectedStatusCodes:
      - 404
  - name: Media Companion
    url: https://media-companion.bricks.tools
    expectedStatusCodes:
      - 500
  - name: Media Resource (Auth0)
    url: https://media-beta.bricks.tw
  - name: Media Resource (Legacy)
    url: https://media.mybigday.com.tw
  - name: MyBigDay User (Legacy)
    url: https://media.mybigday.com.tw

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bricks.tools
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /service-uptime
  logoUrl: https://cdn.mybigday.com.tw/bricks/bricks.png
  name: BRICKS Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
